export const projects = [
  {
    id: 1,
    title: 'Neuro-Adaptive AI Learning Assistant',
    description:
      "AI-powered adaptive learning platform that personalizes curriculum flow and difficulty in real time based on each user's interaction patterns, response accuracy, and session history.",
    tags: ['AI / ML', 'EdTech', 'Full Stack', 'Group Project'],
    techStack: ['Python', 'FastAPI', 'React', 'PostgreSQL', 'ML Models'],
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    liveLink: '#',
    githubLink: 'https://github.com/HARSHHLEDWANI',
    ongoing: true,
    featured: true,
  },
  {
    id: 2,
    title: 'F1 Race Analytics Platform',
    description:
      'Full-stack Formula 1 analytics application with interactive dashboards visualizing driver performance, lap times, pit stop strategies, and season standings across multiple seasons.',
    tags: ['React', 'Node.js', 'Data Viz', 'REST APIs'],
    techStack: ['React.js', 'Node.js', 'REST APIs', 'D3.js', 'TailwindCSS'],
    image: 'https://images.unsplash.com/photo-1617386214930-dae6126db84d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    liveLink: 'https://f1-prediction.vercel.app',
    githubLink: 'https://github.com/HARSHHLEDWANI/F1',
    ongoing: false,
    featured: false,
  },
  {
    id: 3,
    title: 'Zunj Divyang Sanstha — NGO Platform',
    description:
      'Donation and volunteer platform for an NGO with Cashfree Payments integration, real-time campaign tracking, webhook-driven transaction logging, and donor receipt generation.',
    tags: ['Full Stack', 'React', 'Payments', 'Social Impact'],
    techStack: ['Next.js', 'React.js', 'Cashfree API', 'MongoDB', 'Node.js'],
    image: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    liveLink: '#',
    githubLink: 'https://github.com/HARSHHLEDWANI',
    ongoing: false,
    featured: false,
  },
  {
    id: 4,
    title: 'ML Fraud Detection — SecureFlow',
    description:
      'Real-time ML-powered fraud detection system for digital payments with anomaly detection, blockchain-inspired transparency, and a live alert dashboard.',
    tags: ['ML', 'Python', 'Security', 'Backend'],
    techStack: ['Python', 'TensorFlow', 'FastAPI', 'PostgreSQL', 'Redis'],
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    liveLink: '#',
    githubLink: 'https://github.com/HARSHHLEDWANI',
    ongoing: false,
    featured: false,
  },
  {
    id: 5,
    title: 'Phishing Website Detection',
    description:
      'ML classifier that analyzes URL patterns and domain features to detect phishing websites in real time, with browser extension integration and confidence scoring.',
    tags: ['ML', 'Cybersecurity', 'Python', 'Extension'],
    techStack: ['Python', 'Scikit-learn', 'React', 'FastAPI', 'Chrome APIs'],
    image: 'https://images.unsplash.com/photo-1550439062-61a15eec98d1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    liveLink: '#',
    githubLink: 'https://github.com/HARSHHLEDWANI',
    ongoing: false,
    featured: false,
  },
];
